package com.karros.poc.student.school.sql;

public interface SQLFile {
	
	String ASSIGN_SCHOOL_FOR_STUDENT = "insert into SCHOOL_TRANSACTION_RECORD (STUDENT_ID, DISTRICT_CODE, SCHOOL_CODE, SCHOOL_START_DATE, ACTIVE_FLAG) values (?,?,?,?,?)";
	String REASSIGN_SCHOOL_FOR_STUDENT = "update SCHOOL_TRANSACTION_RECORD set SCHOOL_END_DATE=?, ACTIVE_FLAG = 'N' where STUDENT_ID = ? and ACTIVE_FLAG = 'Y' and SCHOOL_END_DATE IS NULL";
	String FETCH_STUDENTS_SCHOOL_AUDIT = "SELECT STUDENT_ID, DISTRICT_CODE, SCHOOL_CODE, SCHOOL_START_DATE, SCHOOL_END_DATE where STUDENT_ID = ?";
}
