spring:
    application.name: student-management-service
    datasource:
      hikari:
        connection-timeout: 20000 
        minimum-idle: 10 
        maximum-pool-size: 20 
        idle-timeout: 10000 
        max-lifetime: 1000 
        auto-commit: true 
      url: jdbc:oracle:thin:@localhost:1521:karrost
      username: KARROS_STUDENT
      password: adGaLwfn_PM2FSr1QP#waKOGCm
      driver-class-name: oracle.jdbc.driver.OracleDriver

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true
      
student:
    school:
      assign: https://school-management-service/school/assign
      reassign: https://school-management-service/school/reassign
      info: https://school-management-service/school/fetchSchoolStudied
    vehicle:
       assign: https://student-transport-service/vehicle/assign
       reassign: https://student-transport-service/vehicle/reassign
       unassign: https://student-transport-service/vehicle/unassign
       info: https://student-transport-service/vehicle/fetchVehicleInfo
server:
    ssl:
      enabled: true
      ciphers: TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384
      enabled-Protocols: [TLSv1.2]
      key-store: classpath:karros-tech-keystore.jks
      key-store-password: Karros%Tech931
    port: 9443
    
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    


#resilience4j.circuitbreaker.metrics.use_legacy_binder: true

resilience4j.circuitbreaker:
  instances:
    assignSchool:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
          - com.karros.poc.student.management.exception.StudentManagementException
    assignVehicle:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.ratelimiter:
  instances:
    service1:
      limitForPeriod: 10
      limitRefreshPeriod: 100000
      timeoutDuration: 1000ms

resilience4j.retry:
  instances:
    retryService1:
      maxRetryAttempts: 5
      waitDuration: 10000

resilience4j.bulkhead:
  instances:
    bulkheadService1:
      maxWaitDuration: 10ms
      max-concurrent-calls: 30

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadService1:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1